### ISSUE TITLE
Footer not updated after changing the children

### ISSUE THREAD

**Issue by solkaz** [nlt2390/react-native-view-more-text#37]
If I update the children of this component, it doesn't recalculate `shouldShowMore`, so updating it from little text to a lot of text (that requires a footer) won't actually trigger calculating if the footer needs to appear. The opposite is true for if I have a lot of text then change it to a little: It will show the "View More" footer even if there is only one line of text

**Comment by micetti** [comment]
Hey @solkaz you can solve this by passing the length of the text that you want to show as key to the `<ViewMoreText` Component
```
<ViewMoreText
  key={props.text.length}          
  numberOfLines={3}
>
  <Text>{props.text}</Text>
</ViewMoreText>
```

**Comment by willdady** [comment]
@micetti that almost certainly won't work if the text is changed for text of equal length e.g "foo" -> "bar".

**Comment by nlt2390** [comment]
> @micetti that almost certainly won't work if the text is changed for text of equal length e.g "foo" -> "bar".

u'r right, can do sth like state = { key: 1 }, then increasing key every time the content changes to force the <ViewMoreText> to update

```javascript
<ViewMoreText
  key={this.state.key}          
>
  <Text>{props.text}</Text>
</ViewMoreText>
```

**Comment by micetti** [comment]
the problem is happening when changing a lot of text to a little of text and the other way round. So changing text of equal length isn't the issue.

**Comment by willdady** [comment]
Digging a little deeper on this the code is relying on `onLayout` to control whether or not to show the footer. If changing the content of a child text component results in an increase or decrease in the number of lines due to wrapping then `onLayout` will fire as expected. If the text changes **do not effect layout** it doesn't fire.

I've hacked around this problem by doing a deep comparison of the children (using [isEqual](https://lodash.com/docs/4.17.15#isEqual)) similar to @nlt2390's suggestion above. Curiously there is an [onTextLayout](https://facebook.github.io/react-native/docs/text#ontextlayout) callback but it's currently undocumented.
